### ISSUE TITLE
Set up content to be easier to manage with gridsome

### ISSUE THREAD

**Issue by elizabethfinedev** [enjoythevue/website#11]
Currently, all the content for the page is just added into the data option in Index.vue.  Do we want to move this to be handled by a data source plugin or just leave it here?

**Comment by bencodezen** [comment]
I think you're right in wanting a data source plugin. I'm not as familiar with the Gridsome ones, but feel free to refactor and try different ones out!

**Comment by bencodezen** [comment]
Went with Netlify CMS thanks to great work by @elizabethfinedev!
