### ISSUE TITLE
Episode Links in Podcast Feed Are Formatted Incorrectly

### ISSUE THREAD

**Issue by codybarr** [enjoythevue/website#119]
If you click on episode links in a podcast app you'll get a 404 because they're formatted like this:

`<link>https://enjoythevue.io//6</link>`

As far as I can tell this seems to be something that has to be configured on the fireside.fm side. I don't believe the Gridsome site is generating any podcast xml.

## For reference

https://feeds.fireside.fm/enjoy-the-vue/rss

![image](https://user-images.githubusercontent.com/4359586/76029175-f51ac600-5f01-11ea-9eb3-dd262e0d119c.png)

**Comment by bencodezen** [comment]
Thanks so much for filing this @codybarr! We'll get on this asap!

**Comment by bencodezen** [comment]
It currently looks like the bug has to do with Fireside, the publishing CMS that we're using. I'm in the midst of troubleshooting it with them, so I've added a workaround for now that should hopefully fix this issue temporarily.

Will keep this issue open when the RSS feed itself is fixed properly.

**Comment by bencodezen** [comment]
@codybarr I think we should be good now! Thanks again for flagging this!

![Screen Shot 2020-03-29 at 4 38 14 PM](https://user-images.githubusercontent.com/4836334/77860176-b9f77400-71db-11ea-8085-ad81e08ac83f.png)

**Comment by codybarr** [comment]
Nice! Thanks @bencodezen
