### ISSUE TITLE
Tessa's picks not appearing as panelist?

### ISSUE THREAD

**Issue by bencodezen** [enjoythevue/website#193]
"It looks like Tessa was added as a panelist but their picks still show up under the guests section. Just a heads up!"

Reported by @drewtown_chi (Twitter)

**Comment by elizabethfinedev** [comment]
I have a PR open for this! https://github.com/enjoythevue/website/pull/198

**Comment by bencodezen** [comment]
Thanks for fixing this @elizabethfinedev!
