### ISSUE TITLE
Landing page design

### ISSUE THREAD

**Issue by bencodezen** [enjoythevue/website#2]
## Problem

Since we have complete control over our site, I'd love for us to take full advantage of design control to create an incredible podcast site experience. 

## Proposed Requirements

- [x] Podcast title
- [x] Signup form with email address and submit button

**Comment by elizabethfinedev** [comment]
I am down to work on this for sure! Maybe we can add to the requirements
- Social links
- Where people can find the podcast
- A navigation area

**Comment by bencodezen** [comment]
Thanks so much for your work on this @elizabethfinedev!
