### ISSUE TITLE
Figure out how to get episode template slug automatically incrementing

### ISSUE THREAD

**Issue by elizabethfinedev** [enjoythevue/website#33]
Right now, the first episode page is hardcoded.  We should make it so it automatically increments for each new episode created.

**Comment by elizabethfinedev** [comment]
Hey @bencodezen, I think I have fixed this.  Apologies if you have already started working on it.  The pr is here: https://github.com/enjoythevue/website/pull/76

**Comment by bencodezen** [comment]
Thanks so much for figuring it out @elizabethfinedev!
